url: http://www.whattrain.co.uk
api: api.trainnotifier.co.uk
trainurl: http://www.trainnotifier.co.uk/train/#!
apiname: whattrain
name: whattrain.co.uk
# exclude showads to not show them
showads: yes
adclient: ca-pub-5958326255808267
adslot: 8666874854
# exclude useanalytics to not use them
useanalytics: yes
analyticsid: UA-40610278-3
analyticsite: whattrain.co.uk

# exclude visual studio and other stuff from deployment
exclude: ["bin",".nuget",".gitattributes",".gitignore","packages.config","CNAME","TrainDelayed.*","traindelayed.*","packages.config","Gemfile*","README.md","LICENSE","Scripts/typings","Scripts/app/*.ts","Scripts/app/*.js.map"]
